name: Test-Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  Linux:
    name: Test Linux
    runs-on: ubuntu-latest
    container: swift:5.8
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: swift test
