name: Test-iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  iOS:
    name: Test iOS 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
            - destination: "OS=17.2,name=iPhone 15 Pro"
              name: "iOS 17.2"
              testPlan: "iOS"
              xcode: "Xcode_15.2"
            - destination: "OS=16.2,name=iPhone 14 Pro"
              name: "iOS 16.2"
              testPlan: "iOS"
              xcode: "Xcode_14.3.1"
    steps:
      - uses: actions/checkout@v4
      - name: ${{ matrix.name }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme Easing -destination "${{ matrix.destination }}" clean test | xcpretty
