name: Test-tvOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  tvOS:
    name: Test tvOS 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "OS=15.2,name=Apple TV"
            name: "tvOS 15.2"
          - destination: "OS=14.5,name=Apple TV"
            name: "tvOS 14.5"
          - destination: "OS=13.4,name=Apple TV"
            name: "tvOS 13.4"
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.name }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme Easing -destination "${{ matrix.destination }}" clean test | xcpretty
