name: Test-tvOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  tvOS:
    name: Test tvOS 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "OS=16.1,name=Apple TV"
            name: "tvOS 16.1"
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.name }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme Easing -destination "${{ matrix.destination }}" clean test | xcpretty
