name: Test-Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
    build:
      runs-on: [ubuntu-latest]
      container: swift:5.8
      steps:
        - uses: actions/checkout@v1
        - name: Linux
            run: swift test --enable-test-discovery --parallel
