name: Test-macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  macOS:
    name: Test macOS (5.4)
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: macOS
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme Easing -destination "platform=macOS" clean test | xcpretty

  Catalyst:
    name: Test Catalyst 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Catalyst
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme Easing -destination "platform=macOS" clean test | xcpretty
