name: Test-iOS

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '*'

jobs:
  iOS:
    name: Test iOS
    runs-on: macOS-latest
    timeout-minutes: 15
    strategy:
        fail-fast: false
        matrix:
        xcode:
            - version: "14.2"
            destination: "platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro"
            - version: "15.2"
            destination: "platform=iOS Simulator,OS=17.2,name=iPhone 15 Pro"
    steps:
        - uses: actions/checkout@v4
        - name: Build and test
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme Easing -destination "${{ matrix.xcode.destination }}" clean test | xcpretty
