name: Test-Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  Linux:
    name: Test Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift-version: ["5.5", "5.6"]  # Example: test with Swift 5.5 and 5.6
    steps:
      - uses: actions/checkout@v4
      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Build and test
        run: |
          swift build
          swift test
